"""Guard: docs/reference/flags.md must stay in sync with the code.

The registry is generated by scripts/gen_flag_registry.py from the actual
OPENRESEARCH_* reads in backend/. If someone adds/removes a flag without
regenerating, this test fails — pointing them at the one-line fix. Keeps the
flag inventory honest without manual upkeep.
"""

from __future__ import annotations

import subprocess
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent


def test_flag_registry_is_fresh() -> None:
    result = subprocess.run(
        [sys.executable, "scripts/gen_flag_registry.py", "--check"],
        cwd=REPO,
        capture_output=True,
        text=True,
    )
    assert result.returncode == 0, (
        "docs/reference/flags.md is stale — regenerate with "
        "`python scripts/gen_flag_registry.py`.\n"
        f"stdout: {result.stdout}\nstderr: {result.stderr}"
    )
