"""Synthesize a deterministic execute-mode cell (``cells.json`` + ``train_cell.py``)
from an ``ExecuteSpec``, so a confidently-detected framework (verl today) is
RUN via the authors' own launch entrypoint instead of hand-authored or
LLM-written per paper.

Background: ``docs/superpowers/specs/2026-07-07-deterministic-any-paper-execute-mode-design.md``
§3/§7/§10. The hand-authored ``scripts/ucpo_execute_cell/train_cell.py`` (the
UCPO prove-now control; real GPU reward 0.25) is the concrete reference this
module generalizes: same setup/launch/reward-bridge shape, but the launch
entrypoint + hydra overrides + reward keys all come from a plan
(``execute_planner.plan``) instead of being hand-typed per paper. The GENERIC
shim (``_SHIM_TEMPLATE``) is IDENTICAL for every paper — only the embedded
``ExecuteSpec`` JSON differs.

Flag-gated default-OFF (``OPENRESEARCH_EXECUTE_SYNTH``); Increment 1a is
additive-only — this module is not called from anywhere yet (that wiring, and
the short-circuit of ``run_with_sdk``, is Increment 1b, per the design's
rollout plan in §7/§9).
"""

from __future__ import annotations

import dataclasses
import json
import logging
import os
import shutil
from pathlib import Path

from backend.agents.rlm import execute_planner

logger = logging.getLogger(__name__)

_VERL_METRICS_ADAPTER_SRC = Path(__file__).resolve().parent / "verl_metrics_adapter.py"


def _flag_enabled() -> bool:
    return os.environ.get("OPENRESEARCH_EXECUTE_SYNTH", "").strip().lower() in (
        "1",
        "true",
        "yes",
    )


# The generated pod-side shim. ``__EXECUTE_SPEC_JSON__`` is replaced with
# ``repr(json.dumps(dataclasses.asdict(spec)))`` at synthesis time (never
# ``.format()`` — the shim body is copied verbatim, and an author's own hydra
# args can legitimately contain ``{``/``}``-shaped tokens that `.format()`
# would mangle). It self-locates (no host-absolute paths), never fabricates a
# reward (bridges through ``verl_metrics_adapter``, value-preserving,
# fail-honest), and never raises out of ``main`` — a failure is always a
# written ``{"status": "failed", ...}`` + exit code 41.
_SHIM_TEMPLATE = '''#!/usr/bin/env python3
"""Synthesized deterministic execute-mode cell (OPENRESEARCH_EXECUTE_SYNTH).

Auto-generated by backend/agents/rlm/execute_cell_synth.py from an
ExecuteSpec. Runs the authors' own launch entrypoint VERBATIM (downscaled per
the spec's ``overrides``) and bridges the authors' OWN reward into the
canonical metrics.json via verl_metrics_adapter (value-preserving,
fail-honest -- never a fabricated 0.0). DO NOT hand-edit -- it is regenerated
on each run_experiment while OPENRESEARCH_EXECUTE_SYNTH is on.

Cell contract (from gke_cell_entrypoint.py / k8s_job_cell_runner):
  invoked as `python train_cell.py --cell-id=<id> --output-dir=<dir>`; also
  reads OPENRESEARCH_CELL_OUTPUT_DIR. Writes <output_dir>/metrics.json.
  Locates sibling modules via Path(__file__).parent (never cwd). Never
  raises out of main.
"""
from __future__ import annotations

import argparse
import json
import os
import subprocess
import sys
from pathlib import Path

CODE_DIR = Path(__file__).resolve().parent

SPEC_JSON = __EXECUTE_SPEC_JSON__
SPEC = json.loads(SPEC_JSON)


def _resolve_output_dir(cli_value):
    if cli_value:
        return Path(cli_value)
    for key in ("OPENRESEARCH_CELL_OUTPUT_DIR", "OUTPUT_DIR", "OPENRESEARCH_ARTIFACT_DIR"):
        val = os.environ.get(key)
        if val:
            return Path(val)
    return CODE_DIR / "cell_output"


def _run(cmd, *, cwd, env, log):
    with open(log, "ab") as fh:
        fh.write(("\\n$ (cwd=%s) %s\\n" % (cwd, " ".join(cmd))).encode())
        fh.flush()
        proc = subprocess.Popen(cmd, cwd=str(cwd), env=env, stdout=fh, stderr=subprocess.STDOUT)
        return proc.wait()


def _write_metrics(out_dir, payload):
    tmp = out_dir / "metrics.json.tmp"
    tmp.write_text(json.dumps(payload, indent=2), encoding="utf-8")
    os.replace(tmp, out_dir / "metrics.json")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument(
        "--cell-id",
        default=os.environ.get("OPENRESEARCH_CELL_ID", SPEC.get("framework", "execute")),
    )
    ap.add_argument("--output-dir", default=None)
    args = ap.parse_args()

    out_dir = _resolve_output_dir(args.output_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    log = out_dir / "train.log"

    def fail(reason, extra=None):
        payload = {"status": "failed", "reason": reason}
        if extra:
            payload.update(extra)
        _write_metrics(out_dir, payload)
        print("CELL FAILED:", reason, flush=True)
        return 41

    env = os.environ.copy()
    env["OUTPUT_DIR"] = str(out_dir)
    env["OPENRESEARCH_CELL_OUTPUT_DIR"] = str(out_dir)
    env["MAX_JOBS"] = os.environ.get("MAX_JOBS", "4")          # cap native-ext compile OOM
    env["HYDRA_FULL_ERROR"] = "1"
    env.setdefault("VLLM_ATTENTION_BACKEND", "XFORMERS")        # avoid flash-attn compile
    env.setdefault("TOKENIZERS_PARALLELISM", "false")

    # (1) Setup: the bundled framework, code-only (--no-deps) -- the cell image
    # already owns the validated heavy stack (torch / vLLM / tensordict / ...).
    for setup_cmd in SPEC.get("setup") or ():
        rc = _run(setup_cmd.split(), cwd=CODE_DIR, env=env, log=log)
        if rc != 0:
            return fail(f"setup command failed (rc={rc}): {setup_cmd}")

    launch = SPEC.get("launch") or {}
    command = launch.get("command", "")
    tokens = command.split()
    if not tokens:
        return fail("execute_spec.json launch.command is empty")
    # Run under the cell's own interpreter (portable across images) instead of
    # a bare "python"/"python3" that may not resolve the same way.
    tokens[0] = sys.executable

    # (2) Optional slice: shrink the authors' own train file to a fast-proof
    # size WITHOUT touching any other hyperparameter -- esp. NOT
    # data.max_response_length (truncating it hides the boxed answer behind a
    # model's chain-of-thought and produces a false near-zero reward).
    data_slice = SPEC.get("data_slice")
    if data_slice:
        train_rel = data_slice.get("train_file")
        slice_rows = int(data_slice.get("slice_rows", 32))
        train_full = CODE_DIR / train_rel
        if not train_full.exists():
            return fail(f"data_slice train_file missing: {train_rel}")
        slice_parquet = out_dir / "train_slice.parquet"
        try:
            import pandas as pd
            pd.read_parquet(train_full).head(slice_rows).to_parquet(slice_parquet)
        except Exception as exc:  # noqa: BLE001
            return fail(f"could not build train slice: {exc}")
        rewritten = False
        for i, tok in enumerate(tokens):
            if tok.startswith("data.train_files="):
                tokens[i] = f"data.train_files={slice_parquet}"
                rewritten = True
                break
        if not rewritten:
            tokens.append(f"data.train_files={slice_parquet}")

    # (2b) Pin the checkpoint dir under out_dir so the run never writes to the
    # authors' ../checkpoint_ds/... (which escapes code/). save_freq=-1 already
    # suppresses writes; this just makes the path hermetic. Mirrors the proven
    # reference (scripts/ucpo_execute_cell/train_cell.py).
    ckpt_dir = out_dir / "checkpoint"
    rewritten_ckpt = False
    for i, tok in enumerate(tokens):
        if tok.startswith("trainer.default_local_dir="):
            tokens[i] = f"trainer.default_local_dir={ckpt_dir}"
            rewritten_ckpt = True
            break
    if not rewritten_ckpt:
        tokens.append(f"trainer.default_local_dir={ckpt_dir}")

    # (3) Append the downscale overrides AFTER the authors' own args (hydra
    # last-wins) -- never before, and never touching an unlisted key.
    for key, value in (launch.get("overrides") or {}).items():
        tokens.append(f"{key}={value}")

    # (4) Run the authors' entrypoint VERBATIM (downscaled).
    train_rc = _run(tokens, cwd=CODE_DIR, env=env, log=log)

    # (5) Bridge the authors' OWN reward -> metrics.json (value-preserving,
    # fail-honest -- never a fabricated 0.0).
    sys.path.insert(0, str(CODE_DIR))
    try:
        from verl_metrics_adapter import write_cell_metrics_from_verl
    except Exception as exc:  # noqa: BLE001
        return fail(f"verl_metrics_adapter import failed: {exc}", {"train_rc": train_rc})

    reward_spec = SPEC.get("reward") or {}
    reward_keys = reward_spec.get("keys") or []
    log_glob = reward_spec.get("log_glob", "$OUTPUT_DIR/*.log")
    framework = SPEC.get("framework", "execute")

    metrics = {"status": "failed"}
    for key in reward_keys:
        metrics = write_cell_metrics_from_verl(
            out_dir, model_key="default", env=framework, baseline="execute",
            log_glob=log_glob, success_rate_key=key,
        )
        if metrics.get("status") == "success":
            metrics["reward_key"] = key
            break

    if metrics.get("status") == "success" and "success_rate" in metrics:
        val = metrics["success_rate"]
        # headline + non-degenerate signals the harness guards read
        metrics["metric"] = val
        metrics["reward"] = val
        metrics["reward_mean"] = val
        try:
            train_bs = int((launch.get("overrides") or {}).get("data.train_batch_size", 1))
        except (TypeError, ValueError):
            train_bs = 1
        slice_rows_for_steps = int((data_slice or {}).get("slice_rows", train_bs)) if data_slice else train_bs
        metrics.setdefault("train_steps", max(1, slice_rows_for_steps // max(train_bs, 1)))
        metrics["train_rc"] = train_rc
        _write_metrics(out_dir, metrics)
        print("CELL METRICS:", json.dumps(metrics), flush=True)
        return 0

    # No reward found -- surface the log tail so the exact reward key can be fixed.
    tail = ""
    try:
        tail = "\\n".join(log.read_text(errors="replace").splitlines()[-40:])
    except OSError:
        pass
    return fail(
        f"{framework} launch produced no readable reward key (see train.log)",
        {"train_rc": train_rc, "tried_keys": list(reward_keys), "log_tail": tail},
    )


if __name__ == "__main__":
    raise SystemExit(main())
'''


def maybe_synthesize_execute_cells(
    code_path: str | Path, *, repo_spec: dict | None = None
) -> dict | None:
    """Write a deterministic single-cell ``cells.json`` + ``train_cell.py`` +
    ``execute_spec.json`` (+ a copy of ``verl_metrics_adapter.py``) when a
    confident ``ExecuteSpec`` can be planned for this repo.

    Returns the synthesized cell dict when it wrote the files, else ``None``
    (a no-op). Surgical + fail-closed on scope: only when the flag is on, and
    only when NEITHER ``cells.json`` NOR ``train_cell.py`` already exists (so
    a hand-/agent-written cell manifest is never clobbered).

    ``repo_spec`` is accepted for forward-compatibility with the wiring site
    (Increment 1b — not implemented here, this module is not called from
    anywhere yet) and is currently unused.
    """
    if not _flag_enabled():
        return None

    code_dir = Path(code_path)
    if (code_dir / "cells.json").exists() or (code_dir / "train_cell.py").exists():
        return None

    spec = execute_planner.plan(code_dir)
    if spec is None:
        return None

    spec_dict = dataclasses.asdict(spec)
    (code_dir / "execute_spec.json").write_text(
        json.dumps(spec_dict, indent=2), encoding="utf-8"
    )

    cell = {
        "id": f"execute-{spec.framework}",
        "model_key": "default",
        "env": spec.framework,
        "baseline": "execute",
        "framework": spec.framework,
        "image_key": spec.image_key,
        "est_vram_gb": spec.est_vram_gb,
    }
    manifest = {
        "_comment": "synthesized by OPENRESEARCH_EXECUTE_SYNTH",
        "cells": [cell],
    }
    (code_dir / "cells.json").write_text(json.dumps(manifest, indent=2), encoding="utf-8")

    shim = _SHIM_TEMPLATE.replace("__EXECUTE_SPEC_JSON__", repr(json.dumps(spec_dict)))
    (code_dir / "train_cell.py").write_text(shim, encoding="utf-8")

    try:
        shutil.copy2(_VERL_METRICS_ADAPTER_SRC, code_dir / "verl_metrics_adapter.py")
    except OSError:
        logger.warning(
            "execute_cell_synth: could not copy verl_metrics_adapter.py into %s", code_dir
        )

    logger.info(
        "execute_cell_synth: synthesized a %s execute cell at %s", spec.framework, code_dir
    )
    return cell
