"""Synthesize a single-cell manifest so a monolithic ``commands.json`` project
routes through the validated GKE cell-matrix instead of the monolithic exec path.

Background (see ``docs/runbooks/2026-07-07-all-runs-triage-and-hardening-handoff.md`` §3):
on ``sandbox=gcp`` the monolithic ``k8s_job_backend.exec`` path never downloads the
GCS-uploaded code into the pod (it overrides the base-image GCS-download entrypoint and
sets no ``OPENRESEARCH_BLOB_CODE_PREFIX``), so a ``commands.json``-only project dies with
``sh: cd: can't cd to .../code``. The cell-matrix path
(``k8s_job_cell_runner.run_matrix`` -> ``gke_cell_entrypoint.py``) already stages code +
uploads results, but only fires when ``code/cells.json`` (valid) + ``code/train_cell.py``
exist (the routing gate in ``primitives.run_experiment``).

This module bridges the gap: when the flag is on and a gcp run would otherwise fall back
to monolithic, it deterministically writes a single-cell ``cells.json`` plus a
``train_cell.py`` shim that runs the monolithic command(s) with the training output pointed
at the entrypoint-provided cell output dir, then routing takes the cell-matrix path with no
change to the gate itself.

Flag-gated default-OFF (``OPENRESEARCH_GKE_SYNTH_CELL`` for GKE and
``OPENRESEARCH_EKS_SYNTH_CELL`` for EKS); a no-op for every other backend, so
``local``/``docker``/``runpod`` stay byte-identical.  EKS is intentionally
cell-only: it must never fall through to the generic monolithic Job path.
"""

from __future__ import annotations

import json
import logging
import os
from pathlib import Path

logger = logging.getLogger(__name__)

_DEFAULT_EST_VRAM_GB = 40.0  # fits a single A100-80; overridable per run.


def _flag_enabled(name: str) -> bool:
    return os.environ.get(name, "").strip().lower() in (
        "1",
        "true",
        "yes",
    )


def _est_vram_gb() -> float:
    raw = os.environ.get("OPENRESEARCH_SYNTH_CELL_VRAM_GB", "").strip()
    if raw:
        try:
            return float(raw)
        except ValueError:
            logger.warning("bad OPENRESEARCH_SYNTH_CELL_VRAM_GB=%r; using default", raw)
    return _DEFAULT_EST_VRAM_GB


# The generated pod-side shim. ``__COMMANDS_LITERAL__`` is replaced with a repr() of the
# ``commands.json`` list at synthesis time (never .format() — the shim body is copied
# verbatim). It self-locates (no host-absolute paths), points the training output at the
# entrypoint-provided cell output dir, forwards SIGTERM for spot-preemption grace, and
# bridges metrics.json to where gke_cell_entrypoint._upload_metrics looks — WITHOUT
# fabricating metrics (an absent metrics.json stays absent = honest no-metrics).
_SHIM_TEMPLATE = '''#!/usr/bin/env python3
"""Synthesized single-cell shim (OPENRESEARCH_GKE_SYNTH_CELL).

Auto-generated by backend/agents/rlm/gke_cell_synth.py to route a monolithic
commands.json through the GKE cell-matrix. DO NOT hand-edit — it is regenerated
on each run_experiment while the flag is on.
"""
from __future__ import annotations

import argparse
import os
import shutil
import signal
import subprocess
import sys
from pathlib import Path

CODE_DIR = Path(__file__).resolve().parent
COMMANDS = __COMMANDS_LITERAL__  # list[str], baked from commands.json


def _resolve_output_dir(cli_output_dir):
    for cand in (
        cli_output_dir,
        os.environ.get("OPENRESEARCH_CELL_OUTPUT_DIR"),
        os.environ.get("OUTPUT_DIR"),
        os.environ.get("OPENRESEARCH_ARTIFACT_DIR"),
    ):
        if cand:
            return Path(cand)
    return CODE_DIR / "cell_output"


def _bridge_metrics(output_dir):
    """Ensure output_dir/metrics.json exists so the entrypoint uploads it.

    A well-behaved train.py honors OUTPUT_DIR and writes there directly; if it wrote
    metrics.json into the code dir (cwd) instead, copy the newest one over. Never
    fabricate metrics — if none exists anywhere, leave it absent (honest no-metrics).
    """
    dest = output_dir / "metrics.json"
    if dest.is_file():
        return
    candidates = sorted(
        CODE_DIR.glob("**/metrics.json"),
        key=lambda p: p.stat().st_mtime,
        reverse=True,
    )
    for src in candidates:
        if src.resolve() == dest.resolve():
            continue
        shutil.copyfile(src, dest)
        return


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--cell-id", default=os.environ.get("OPENRESEARCH_CELL_ID", "monolithic"))
    ap.add_argument("--output-dir", default=None)
    args = ap.parse_args()

    output_dir = _resolve_output_dir(args.output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    env = dict(os.environ)
    env["OUTPUT_DIR"] = str(output_dir)
    env["OPENRESEARCH_ARTIFACT_DIR"] = str(output_dir)
    env["OPENRESEARCH_CELL_OUTPUT_DIR"] = str(output_dir)
    env["OPENRESEARCH_CELL_ID"] = args.cell_id

    proc = None

    def _forward(signum, _frame):
        if proc is not None and proc.poll() is None:
            proc.send_signal(signum)

    signal.signal(signal.SIGTERM, _forward)
    signal.signal(signal.SIGINT, _forward)

    rc = 0
    for cmd in COMMANDS:
        proc = subprocess.Popen(cmd, shell=True, cwd=str(CODE_DIR), env=env)
        rc = proc.wait()
        if rc != 0:
            break

    _bridge_metrics(output_dir)
    return rc


if __name__ == "__main__":
    sys.exit(main())
'''


def _load_commands(code_dir: Path) -> list[str]:
    """Return the non-blank shell strings from code/commands.json (bare list form)."""
    manifest = code_dir / "commands.json"
    if not manifest.is_file():
        return []
    try:
        data = json.loads(manifest.read_text(encoding="utf-8"))
    except Exception:  # noqa: BLE001 — malformed manifest -> synthesize nothing, fail-soft
        return []
    if not isinstance(data, list):
        return []
    return [str(c).strip() for c in data if str(c).strip()]


def maybe_synthesize_k8s_cell(code_path: "str | Path", backend_kind: str) -> dict | None:
    """Write a single-cell manifest when an explicit cloud flag allows it.

    Returns the synthesized cell dict when it wrote the files, else ``None`` (a no-op).
    Surgical + fail-closed on scope: only ``backend_kind == "gcp"`` with
    ``OPENRESEARCH_GKE_SYNTH_CELL`` on or ``backend_kind == "aws"`` with
    ``OPENRESEARCH_EKS_SYNTH_CELL`` on, and only when NEITHER ``cells.json`` NOR
    ``train_cell.py`` already exists (so a hand-/agent-written cell manifest is
    never clobbered — e.g. prj_618's workaround).
    """
    flag_name = {
        "gcp": "OPENRESEARCH_GKE_SYNTH_CELL",
        "aws": "OPENRESEARCH_EKS_SYNTH_CELL",
    }.get(backend_kind)
    if flag_name is None or not _flag_enabled(flag_name):
        return None

    code_dir = Path(code_path)
    # Don't touch a project that already has (or is mid-writing) a cell manifest.
    if (code_dir / "cells.json").exists() or (code_dir / "train_cell.py").exists():
        return None

    commands = _load_commands(code_dir)
    if not commands:
        return None  # nothing monolithic to wrap; run_experiment's own guard handles this

    cell = {
        "id": "monolithic",
        "model_key": "default",
        "env": "default",
        "baseline": "monolithic",
        "est_vram_gb": _est_vram_gb(),
    }
    manifest = {
        "_comment": f"synthesized by {flag_name} — wraps monolithic commands.json "
        f"for the {backend_kind} cell-matrix path",
        "cells": [cell],
    }
    (code_dir / "cells.json").write_text(
        json.dumps(manifest, indent=2), encoding="utf-8"
    )
    shim = _SHIM_TEMPLATE.replace("__COMMANDS_LITERAL__", repr(commands))
    (code_dir / "train_cell.py").write_text(shim, encoding="utf-8")

    logger.info(
        "k8s_cell_synth: wrapped %d command(s) into a single-cell manifest at %s",
        len(commands),
        code_dir,
    )
    return cell


def maybe_synthesize_gke_cell(code_path: "str | Path", backend_kind: str) -> dict | None:
    """Backward-compatible GKE-named entry point for existing callers/tests."""
    return maybe_synthesize_k8s_cell(code_path, backend_kind)
