"""Phase 2B — preflight IMPORT smoke (the executing half of preflight "TDD").

The static AST gate (``preflight_ast.scan_code_dir``) reads the code; this runs an
actual cheap *test* INSIDE the sandbox before the GPU training command: it imports
every third-party dependency the agent's code declares and fails loudly if one does
not resolve. That catches the ``ModuleNotFoundError`` class (e.g. ``import
matplotlib`` with no requirements entry) in SECONDS on CPU, instead of after a GPU
pod spins up and training starts.

Design (robust + low-false-positive):
  * It probes ONLY the *imported dependency roots* (AST-collected ``import X`` /
    ``from X import …``), NEVER the agent's own modules — so it can never trigger
    "training on import" side effects. Importing a missing dep IS a real bug, so the
    false-positive rate is essentially zero.
  * It runs with ``CUDA_VISIBLE_DEVICES=""`` (never touches the GPU) and inherits the
    sandbox's isolation (network/mem/fs controls, hard command timeout).
  * Gated behind ``OPENRESEARCH_PREFLIGHT_SMOKE`` (default OFF) — opt-in, since even an
    import executes code; the sandbox is the isolation boundary.

The emitted script is self-contained (stdlib only) because it runs in the sandbox
where ``backend`` is not importable — mirroring the ``gpu_cell_runner`` / ``rubric_
guard`` copyable-helper pattern, but generated rather than copied.
"""
from __future__ import annotations

import os
from pathlib import Path

# A command carrying this marker short-circuits the sandbox command loop on failure
# (skip the remaining training commands) — see _execute_in_sandbox.
MARKER = "# reprolab:preflight-smoke"

_EMITTED_NAME = "_preflight_smoke.py"

# Self-contained, stdlib-only. Runs in the sandbox CWD == code/.
SMOKE_SCRIPT = r'''#!/usr/bin/env python3
"""Auto-generated by ReproLab preflight_smoke — do not edit. Probes that every
third-party dependency the agent's code imports actually resolves. Exits 3 on any
failure so the harness skips the GPU training command. Never imports the agent's own
modules (no training-on-import)."""
import ast
import importlib
import json
import os
import pathlib
import sys

os.environ.setdefault("CUDA_VISIBLE_DEVICES", "")  # never touch the GPU

HERE = pathlib.Path(__file__).resolve().parent
_SELF = pathlib.Path(__file__).name

# Local modules/packages — never probed (avoid executing the agent's own code).
_local = set()
for _p in HERE.iterdir():
    if _p.suffix == ".py":
        _local.add(_p.stem)
    elif _p.is_dir() and any(_p.glob("*.py")):
        _local.add(_p.name)

# 1. Identify entry-point files (the code that actually executes).
#    Priority order: named entry points, then cells.json-named scripts.
#    If NONE found, fall back to scanning every .py (legacy behaviour, non-cell papers).
_entry_points: list = []

# Fixed-name entry points
for _ep_name in ("train_cell.py", "train.py", "main.py"):
    _ep = HERE / _ep_name
    if _ep.exists():
        _entry_points.append(_ep.resolve())

# cells.json-named scripts
_cells_json = HERE / "cells.json"
if _cells_json.exists():
    try:
        _cells_raw = json.loads(_cells_json.read_text(encoding="utf-8"))
        # cells.json may be a list or {"cells": [...]}
        _cells_list = _cells_raw if isinstance(_cells_raw, list) else _cells_raw.get("cells", [])
        for _cell in _cells_list:
            if not isinstance(_cell, dict):
                continue
            for _key in ("script", "entry", "trainer"):
                _val = _cell.get(_key)
                if isinstance(_val, str) and _val:
                    _candidate = HERE / _val
                    if _candidate.exists():
                        _rp = _candidate.resolve()
                        if _rp not in _entry_points:
                            _entry_points.append(_rp)
    except Exception:
        pass  # malformed cells.json: do not crash the smoke

# 2. Collect top-level dependency roots via import-closure BFS from entry points.
#    If no entry point found, fall back to scanning every .py (legacy behaviour).
roots = set()

def _extract_imports_from_file(py_path):
    """Parse a single file and yield (top_name, is_local) pairs for module-level imports."""
    try:
        tree = ast.parse(py_path.read_text(encoding="utf-8"))
    except Exception:
        return  # SyntaxError etc. — static AST gate's job
    # MODULE-LEVEL imports only (direct children of module body): deliberatey skip
    # imports nested in functions/classes (lazy imports) and inside try/if blocks
    # (ImportError-guarded optionals).
    for node in tree.body:
        if isinstance(node, ast.Import):
            for alias in node.names:
                top = alias.name.split(".")[0]
                if top:
                    is_local = (HERE / (top + ".py")).exists() or (HERE / top / "__init__.py").exists()
                    yield top, is_local
        elif isinstance(node, ast.ImportFrom):
            if node.level == 0 and node.module:  # absolute imports only
                top = node.module.split(".")[0]
                if top:
                    is_local = (HERE / (top + ".py")).exists() or (HERE / top / "__init__.py").exists()
                    yield top, is_local

if _entry_points:
    # BFS over the local import graph reachable from entry points.
    _visited: set = set()
    _queue: list = list(_entry_points)
    while _queue:
        _py = _queue.pop(0)
        if _py in _visited:
            continue
        _visited.add(_py)
        if _py.name == _SELF:
            continue
        for _top, _is_local in _extract_imports_from_file(_py):
            if _is_local:
                # Follow the local module into the BFS (do NOT probe it as third-party).
                _local_file = HERE / (_top + ".py")
                _local_pkg = HERE / _top / "__init__.py"
                if _local_file.exists():
                    _rp = _local_file.resolve()
                    if _rp not in _visited:
                        _queue.append(_rp)
                elif _local_pkg.exists():
                    _rp = _local_pkg.resolve()
                    if _rp not in _visited:
                        _queue.append(_rp)
            else:
                # Third-party root — add to probe set.
                roots.add(_top)
else:
    # No identifiable entry point: fall back to whole-dir scan (legacy behaviour).
    # Non-cell papers, minimal harness setups, etc. are unaffected.
    for py in sorted(HERE.rglob("*.py")):
        if py.name == _SELF:
            continue
        for _top, _is_local in _extract_imports_from_file(py):
            if not _is_local:
                roots.add(_top)

# 3. Probe each third-party root (skip locals + __future__).
failures = []
probed = []
for r in sorted(roots):
    if not r or r in _local or r == "__future__":
        continue
    probed.append(r)
    if r == "backend":
        # In-repo harness import (`from backend.agents.rlm... import X`): the sandbox is
        # FLAT, so `backend` is not importable. The copied helpers live next to train.py
        # — import them BARE: `from provenance import emit_provenance`, `from rubric_guard
        # import assert_metrics_schema`, `from cell_scheduler import ...`.
        failures.append({
            "module": "backend",
            "error_type": "SandboxImportError",
            "error": ("in-repo 'backend.*' import is unavailable in the flat sandbox; "
                      "rewrite to a bare import of the copied helper, e.g. 'from provenance "
                      "import emit_provenance' (NOT 'from backend.agents.rlm.provenance import ...')"),
        })
        continue
    try:
        importlib.import_module(r)
    except BaseException as exc:  # catch SystemExit/KeyboardInterrupt from odd deps too
        failures.append({
            "module": r,
            "error_type": type(exc).__name__,
            "error": str(exc)[:300],
        })

result = {"ok": not failures, "probed": probed, "failures": failures}
try:
    (HERE / "preflight_smoke_result.json").write_text(json.dumps(result, indent=2), encoding="utf-8")
except OSError:
    pass

if failures:
    print("PREFLIGHT IMPORT SMOKE FAILED: " + json.dumps(failures), file=sys.stderr)
    sys.exit(3)
print("PREFLIGHT IMPORT SMOKE OK — %d dependency root(s) resolve" % len(probed))
'''


def is_enabled() -> bool:
    """True unless ``OPENRESEARCH_PREFLIGHT_SMOKE`` is explicitly disabled.

    Default ON since 2026-06-15 (issue #5): a CPU-only import probe that catches a
    missing dependency in seconds before any GPU dispatch (the Adam run logged
    missing_module ×3 among 20 failed experiment runs). Set the flag to
    ``0``/``false``/``no``/``off`` (or empty) to disable.
    """
    return os.environ.get("OPENRESEARCH_PREFLIGHT_SMOKE", "on").strip().lower() not in (
        "0", "false", "no", "off", "",
    )


def emit(code_dir: Path) -> Path:
    """Write the self-contained smoke script into ``code_dir``; return its path."""
    target = code_dir / _EMITTED_NAME
    target.write_text(SMOKE_SCRIPT, encoding="utf-8")
    return target


def smoke_command(code_dir: Path, *, uses_sandbox_workdir: bool = False) -> str:
    """Return the sandbox command that runs the smoke (carrying :data:`MARKER`).

    Resolves a working interpreter at run time (``python3`` then ``python``) so the
    step is robust across the runpod image (``python``/``python3`` present) and the
    local per-run venv. GPU is hidden for the probe.
    """
    # Runtime backends normally execute commands in their work directory.  Local
    # callers retain the explicit cd for compatibility, while RunPod must not
    # embed the orchestrator's relative/absolute host path inside the remote
    # shell command.
    change_dir = "" if uses_sandbox_workdir else f'cd "{code_dir}" && '
    return (
        f"sh -c '{change_dir}P=$(command -v python3 || command -v python) && "
        f'CUDA_VISIBLE_DEVICES="" "$P" {_EMITTED_NAME}\'  {MARKER}'
    )


__all__ = ["MARKER", "SMOKE_SCRIPT", "is_enabled", "emit", "smoke_command"]
